# Generated by Django 2.2.2 on 2020-07-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('address', models.CharField(max_length=100)),
                ('subject', models.TextField()),
                ('file_name', models.TextField()),
            ],
            options={
                'verbose_name': 'API log',
                'verbose_name_plural': 'API logs',
            },
        ),
    ]
