# Generated by Django 2.2.2 on 2021-04-02 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apilogs_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apilogs',
            old_name='address',
            new_name='customer',
        ),
    ]
