# Generated by Django 3.2.4 on 2021-06-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_apilogs_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apilogs',
            old_name='file_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='apilogs',
            old_name='subject',
            new_name='type',
        ),
    ]
