# Generated by Django 3.2.4 on 2021-06-18 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'entities',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'subcategories',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_set', to=settings.AUTH_USER_MODEL)),
                ('user_group', models.ManyToManyField(to='pmoReporting.Entity')),
            ],
            options={
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='PmoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('location_type', models.CharField(max_length=50)),
                ('initiative_type', models.CharField(max_length=50)),
                ('initiative_product', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=50)),
                ('implementation_deadline', models.DateField(blank=True, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('initiative_year', models.CharField(max_length=5)),
                ('actual_01', models.FloatField(blank=True, default=0.0, null=True)),
                ('actual_02', models.FloatField(blank=True, default=0.0, null=True)),
                ('actual_03', models.FloatField(blank=True, default=0.0, null=True)),
                ('actual_04', models.FloatField(blank=True, default=0.0, null=True)),
                ('actual_05', models.FloatField(blank=True, default=0.0, null=True)),
                ('actual_06', models.FloatField(blank=True, default=0.0, null=True)),
                ('actual_07', models.FloatField(blank=True, default=0.0, null=True)),
                ('actual_08', models.FloatField(blank=True, default=0.0, null=True)),
                ('actual_09', models.FloatField(blank=True, default=0.0, null=True)),
                ('actual_10', models.FloatField(blank=True, default=0.0, null=True)),
                ('actual_11', models.FloatField(blank=True, default=0.0, null=True)),
                ('actual_12', models.FloatField(blank=True, default=0.0, null=True)),
                ('budget_01', models.FloatField(blank=True, default=0.0, null=True)),
                ('budget_02', models.FloatField(blank=True, default=0.0, null=True)),
                ('budget_03', models.FloatField(blank=True, default=0.0, null=True)),
                ('budget_04', models.FloatField(blank=True, default=0.0, null=True)),
                ('budget_05', models.FloatField(blank=True, default=0.0, null=True)),
                ('budget_06', models.FloatField(blank=True, default=0.0, null=True)),
                ('budget_07', models.FloatField(blank=True, default=0.0, null=True)),
                ('budget_08', models.FloatField(blank=True, default=0.0, null=True)),
                ('budget_09', models.FloatField(blank=True, default=0.0, null=True)),
                ('budget_10', models.FloatField(blank=True, default=0.0, null=True)),
                ('budget_11', models.FloatField(blank=True, default=0.0, null=True)),
                ('budget_12', models.FloatField(blank=True, default=0.0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmoReporting.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmoReporting.subcategory')),
            ],
            options={
                'verbose_name_plural': 'pmo data',
            },
        ),
    ]
