# Generated by Django 3.2.4 on 2021-08-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabData',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('step', models.CharField(blank=True, max_length=50, null=True)),
                ('stream', models.CharField(blank=True, max_length=200, null=True)),
                ('feature', models.CharField(blank=True, max_length=50, null=True)),
                ('est_dev_hrs', models.FloatField(blank=True, null=True)),
                ('est_cost_sek', models.FloatField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('hl_payer', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CAB data',
                'verbose_name_plural': 'CAB data',
            },
        ),
    ]
