# Generated by Django 3.2.4 on 2021-06-18 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'groups',
            },
        ),
        migrations.CreateModel(
            name='highlight_tracker_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Value', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'highlight tracker settings',
            },
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'subject groups',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_area', models.ManyToManyField(to='HighlightTracker.Area')),
                ('user_country', models.ManyToManyField(to='HighlightTracker.Country')),
                ('user_group', models.ManyToManyField(to='HighlightTracker.Group')),
            ],
            options={
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='highlight_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_Group', models.CharField(max_length=50)),
                ('Improvement_Identified', models.CharField(max_length=50)),
                ('Action_description', models.TextField(blank=True, null=True)),
                ('Responsible_person', models.CharField(blank=True, max_length=50, null=True)),
                ('Completion_Date', models.DateField(blank=True, null=True)),
                ('Action_status', models.CharField(blank=True, max_length=50, null=True)),
                ('Comments', models.TextField(blank=True, null=True)),
                ('row_Year', models.CharField(max_length=10)),
                ('row_Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HighlightTracker.area')),
                ('row_Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HighlightTracker.group')),
                ('row_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HighlightTracker.country')),
            ],
            options={
                'verbose_name_plural': 'highlight data',
            },
        ),
    ]
