# Generated by Django 3.2.4 on 2021-11-19 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowGroupNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'cash flow group names',
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('approval_level_1_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('approval_level_2_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('approval_level_3_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('approval_level_4_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('approval_level_5_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('approval_level_6_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('approval_level_7_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('approval_level_8_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('approval_level_9_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('approval_level_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_level_1', to=settings.AUTH_USER_MODEL)),
                ('approval_level_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_level_2', to=settings.AUTH_USER_MODEL)),
                ('approval_level_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_level_3', to=settings.AUTH_USER_MODEL)),
                ('approval_level_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_level_4', to=settings.AUTH_USER_MODEL)),
                ('approval_level_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_level_5', to=settings.AUTH_USER_MODEL)),
                ('approval_level_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_level_6', to=settings.AUTH_USER_MODEL)),
                ('approval_level_7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_level_7', to=settings.AUTH_USER_MODEL)),
                ('approval_level_8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_level_8', to=settings.AUTH_USER_MODEL)),
                ('approval_level_9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_level_9', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='InvestmentHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=50)),
                ('requested_amount', models.FloatField()),
                ('why', models.TextField(blank=True, null=True)),
                ('what', models.TextField(blank=True, null=True)),
                ('how', models.TextField(blank=True, null=True)),
                ('alternative', models.TextField(blank=True, null=True)),
                ('env_impact', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvestmentRequest.companies')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'investment headers',
            },
        ),
        migrations.CreateModel(
            name='InvestmentRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('year_01', models.FloatField(blank=True, null=True)),
                ('year_02', models.FloatField(blank=True, null=True)),
                ('year_03', models.FloatField(blank=True, null=True)),
                ('year_04', models.FloatField(blank=True, null=True)),
                ('year_05', models.FloatField(blank=True, null=True)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvestmentRequest.investmentheader')),
            ],
            options={
                'verbose_name_plural': 'investment rows',
            },
        ),
        migrations.CreateModel(
            name='CashFlowNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('cash_flow_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvestmentRequest.cashflowgroupnames')),
            ],
            options={
                'verbose_name_plural': 'cash flow names',
            },
        ),
        migrations.CreateModel(
            name='ApprovalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_1_status', models.CharField(blank=True, max_length=50, null=True)),
                ('level_2_status', models.CharField(blank=True, max_length=50, null=True)),
                ('level_3_status', models.CharField(blank=True, max_length=50, null=True)),
                ('level_4_status', models.CharField(blank=True, max_length=50, null=True)),
                ('level_5_status', models.CharField(blank=True, max_length=50, null=True)),
                ('level_6_status', models.CharField(blank=True, max_length=50, null=True)),
                ('level_7_status', models.CharField(blank=True, max_length=50, null=True)),
                ('level_8_status', models.CharField(blank=True, max_length=50, null=True)),
                ('level_9_status', models.CharField(blank=True, max_length=50, null=True)),
                ('level_1_date', models.DateField(blank=True, null=True)),
                ('level_2_date', models.DateField(blank=True, null=True)),
                ('level_3_date', models.DateField(blank=True, null=True)),
                ('level_4_date', models.DateField(blank=True, null=True)),
                ('level_5_date', models.DateField(blank=True, null=True)),
                ('level_6_date', models.DateField(blank=True, null=True)),
                ('level_7_date', models.DateField(blank=True, null=True)),
                ('level_8_date', models.DateField(blank=True, null=True)),
                ('level_9_date', models.DateField(blank=True, null=True)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvestmentRequest.investmentheader')),
            ],
            options={
                'verbose_name_plural': 'approval data',
            },
        ),
    ]
