# Generated by Django 3.2.4 on 2021-11-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentRequest', '0003_attachments_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentrow',
            name='type_group',
            field=models.CharField(default='some_grouo', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentrow',
            name='type_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
