# Generated by Django 3.2.4 on 2021-11-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentRequest', '0004_auto_20211125_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentheader',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
