# Generated by Django 3.2.4 on 2021-12-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentRequest', '0007_auto_20211130_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentheader',
            name='requested_amount',
            field=models.IntegerField(),
        ),
    ]
